CoreKamp/Controllers/MessageController.cs
using CoreKamp.BusinessLayer.Concrete;
using CoreKamp.DataAccessLayer.Concrete;
using CoreKamp.DataAccessLayer.EntityFramework;
using CoreKamp.EntityLayer.Concrete;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Linq;

namespace CoreKamp.Controllers
{
   
    public class MessageController : Controller
    {
        Message2Manager message2Manager = new Message2Manager(new EfMessage2Repository());
        Context context = new Context();
        public IActionResult InBox()
        {
           
            var username = User.Identity.Name;
            var usermail = context.Users.Where(x => x.UserName == username).Select(y => y.Email).FirstOrDefault();
            var writerID = context.Writers.Where(x => x.WriterMail == usermail).Select(y => y.WriterID).FirstOrDefault();
            var values = message2Manager.GetInBoxListByWriter(writerID);
            return View(values);
        }
        public IActionResult SendBox()
        {
            var username = User.Identity.Name;
            var usermail = context.Users.Where(x => x.UserName == username).Select(y => y.Email).FirstOrDefault();
            var writerID = context.Writers.Where(x => x.WriterMail == usermail).Select(y => y.WriterID).FirstOrDefault();
            var values = message2Manager.GetSendBoxListByWriter(writerID);
            return View();
        }


        public IActionResult MessageDetails(int id)
        {
            var value=message2Manager.TGetById(id);
            return View(value);
        }

        [HttpGet]
        public IActionResult SendMessage()
        {
            return View();
        }

        [HttpPost]
        public IActionResult SendMessage(Message2 message2)
        {
            var username = User.Identity.Name;
            var usermail = context.Users.Where(x => x.UserName == username).Select(y => y.Email).FirstOrDefault();
            var writerID = context.Writers.Where(x => x.WriterMail == usermail).Select(y => y.WriterID).FirstOrDefault();
            message2.SenderID = writerID;
            message2.ReceiverID = 2;
            message2.MessageStatus = true;
            message2.MessageDate=Convert.ToDateTime(DateTime.Now.ToShortDateString());
            message2Manager.Add(message2);
            return RedirectToAction("InBox");
        }
    }
}

CoreKamp/Views/Message/InBox.cshtml
@using CoreKamp.EntityLayer.Concrete
@model List<Message2>
@{
    ViewData["Title"] = "InBox";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}

<h1>Gelen Kutusu</h1>
<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>Konu</th>
        <th>Gönderen</th>
        <th>Tarih</th>
        <th>Mesajı Aç</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
        <th>@item.MessageID</th>
        <td>@item.Subject</td>
        <td>@item.SenderUser.WriterName</td>
        <td>@(((DateTime)item.MessageDate).ToString("dd.MMM.yyyy"))</td>   
        
        <td><a href="/Message/MessageDetails/@item.MessageID" class="btn btn-warning">Mesajı Aç</a></td>

        </tr>
    }
</table>
<a href="/Message/SendMessage/" class="btn btn-primary">Yeni Mesaj Oluştur</a>

CoreKamp/Views/Message/MessageDetails.cshtml
@model CoreKamp.EntityLayer.Concrete.Message2
@{
    ViewData["Title"] = "MessageDetails";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}

<h1>Mesaj Detay Sayfası</h1>
<br />
    @Html.Label("Mesaj ID")
    @Html.TextBoxFor(x=>x.MessageID,new{@class="form-control"})
    <br />
    @Html.Label("Mesaj Başlığı")
    @Html.TextAreaFor(x=>x.Subject,new{@class="form-control"})
    <br />
      @Html.Label("Mesaj İçeriği")
    @Html.TextAreaFor(x=>x.MessageDetails,10,3,new{@class="form-control"})
    <br />
   
    <button class="btn btn-success">Mesajlara Dön</button>

CoreKamp/Views/Message/SendBox.cshtml
@using CoreKamp.EntityLayer.Concrete
@model List<Message2>
@{
    ViewData["Title"] = "SendBox";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}

<h1>Giden Kutusu</h1>
<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>Konu</th>
        <th>Alıcı</th>
        <th>Tarih</th>
        <th>Mesajı Aç</th>
    </tr>
    @foreach (var item in Model)
    {
        <tr>
        <th>@item.MessageID</th>
        <td>@item.Subject</td>
        <td>@item.ReceiverUser.WriterName</td>
        <td>@(((DateTime)item.MessageDate).ToString("dd.MMM.yyyy"))</td>   
        
        <td><a href="/Message/MessageDetails/@item.MessageID" class="btn btn-warning">Mesajı Aç</a></td>

        </tr>
    }
</table>
<a href="/Message/SendMessage/" class="btn btn-primary">Yeni Mesaj Oluştur</a>

CoreKamp/Views/Message/SendMessage.cshtml
@model CoreKamp.EntityLayer.Concrete.Message2

@{
    ViewData["Title"] = "SendMessage";
    Layout = "~/Views/Shared/WriterLayout.cshtml";
}
<h1>Yeni Mesaj Oluştur</h1>
<br />
  @using (Html.BeginForm("SendMessage", "Message", FormMethod.Post))
  {
      @Html.Label("Alıcı")
     @* @Html.TextBoxFor(x=>x.Subject,new{@class="form-control"})*@
     <input type="text" class="form-control"/>
      <br />
      @Html.Label("Konu")
      @Html.TextBoxFor(x=>x.Subject,new{@class="form-control"})
      <br />
      @Html.Label("Mesajınız")
      @Html.TextAreaFor(x=>x.MessageDetails,15,3, new{@class="form-control"})
      <br />
      <button class="btn btn-info">Mesajı Gönder</button>
  }